name: soci_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  animated_splash_screen: ^1.3.0
  audioplayers: ^3.0.1
  google_maps_flutter: ^2.0.10
  lottie: ^2.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: times
      fonts:
        - asset: fonts/times.ttf
